# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Melee
tagline:             'Material scientist'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             '/blog'
paginate:            5
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
